### ISSUE TITLE
{{ page.content|toc }} not working

### ISSUE THREAD

**Issue by lid3rs** [Sommerregen/grav-plugin-toc#8] opened 2015-11-07 20:58 UTC
Good day, have set up you plugin, @version 1.3.1.
{{ page.content|toc }} gives me the full content of the page.

Also a question: my TOC should be displayed outside of MD, in separate template partial. How to say to app, that "you have to use headings from MD, but print these only in this template partial"?

And what is the correct way to insert TOC in MD? See screenshot. Is it OK?
![screen shot 2015-11-07 at 20 58 58](https://cloud.githubusercontent.com/assets/1872001/11017299/75138994-8592-11e5-952c-9e5e218aa073.png)

**Comment by Sommerregen** [comment] 2015-11-09 19:40
Dear @lid3rs,

the `toc` filter is designed to return the content with all the `[TOC]` or `[MINITOC]` marker being replaced by their rendered table of contents counterparts. The way how the table of contents is rendered defines the `partials/toc.html.twig` template.

For your convenience I now added a filter `{% set toc = page.content|tocify %}` (in the develop branch), which returns you an array of all headings in the format

``` php
['list' => ..., 'type' => ..., 'heading' => ...]
```

where `type` is either "toc" or "minitoc", `list` contains all headings of the format

``` php
['tag' => ..., 'level' => ..., 'indent' => ..., 'text' => ..., 'id' => ...]
```

and `heading` is either "null" (toc) or the current (sub-)section in case of a minitoc. You can call the `tocify` filter anywhere in Twig. Otherwise I recommend you to modify `partials/toc.html.twig` i.e., cut & paste its contents into another file called `partials/toc_default.html.twig`, include it in the now empty template and perform your modifications before.

**Comment by OleVik** [comment] 2015-12-02 22:09
Using the current development branch, and including it in a post template like so:

```
{% set toc = page.content|tocify %}
{% include 'partials/toc_default.html.twig' %}
```

Where `partials/toc_default.html.twig` is a copy in the theme of `partials/toc.html.twig` from the plugin, the returned HTML is an empty unordered list. Could you expand on how to include the TOC in a template, rather than page/post through `[TOC]`?

**Comment by Sommerregen** [comment] 2015-12-06 15:16
@OleVik Sorry for the long silence. I'm loaded with other stuff at the moment, but I'll see what I can. The reason for having the `tocify` filter presently only in the develop branch is that the API of this filter is not final and is open for discussion. Further I haven't had the time to test it agains various test cases and may have some bugs I'm not aware of. If you have something in mind how it should behave and used, I really like to hear :smile: !

Currently you are right, the `tocify` filter was buggy, see the bugfix https://github.com/Sommerregen/grav-plugin-toc/commit/70ab3e8a2018a3f6f84cba7d2f329b3efc4456f7 . But now it only returns a list with all headings in the format

``` php
['tag' => ..., 'level' => ..., 'indent' => ..., 'text' => ..., 'id' => ...]
```

To use it in your template the best is to follow these steps. Assuming you have Antimatter installed add a TOC section in you sidebar via

``` twig
{% if config.plugins.toc.enabled %}
<div class="sidebar-content">
    <h4>Table Of Contents</h4>
    {% include 'partials/toc.html.twig' with {'page': grav.page} %}
</div>
{% endif %}
```

In your `partials/toc.html.twig` you then put (as an example)

``` twig
{% set toc = page.content|tocify %}
<ul class="toc-navigation">
  {% for element in toc %}
    <li>{{ element.text }}</li>
  {% endfor %}
</ul>
```

which will show you all headings as an unordered list. I hope that's the thing you are looking to.

BTW: The location where the toc templates are lying has changed, thus be sure to update the plugin in order to refelct the changes made in https://github.com/Sommerregen/grav-plugin-toc/commit/8bba9c9555955d1aeb1e187d4c2da2415435984a .

**Comment by lid3rs** [comment] 2017-01-20 08:05
Found an issue with cache.
When cache is enabled and {% set toc = p.content|tocify %} is used, system gives error on certain pages: Call to a member function get() on a non-object.

user/plugins/toc/classes/Toc.php
[481]  if ($this->options->get('slug.truncate')) {... 


After removing {% set toc = p.content|tocify %}, everything is back to normal.

This happens only if cache is enabled.

**Comment by Sommerregen** [comment] 2017-02-05 18:30
@lid3rs Ok, thanks for the info 👍

**Comment by lid3rs** [comment] 2017-02-23 15:50
@Sommerregen Good day, just wanted to figure out status, will it be repaired or already repaired? I still keep getting error. :(

**Comment by Sommerregen** [comment] 2017-03-19 19:00
Hi @lid3rs ,

yes it will be repaired. However I haven't merged it yet. Will do soon.

**Comment by lid3rs** [comment] 2017-04-05 10:20
@Sommerregen Any progress on this case?

**Comment by Sommerregen** [comment] 2017-04-05 19:24
@lid3rs Currently, the state comes to an halt. Can you do me a favor and checkout the develop branch and test it?

**Comment by lid3rs** [comment] 2017-04-06 13:42
@Sommerregen  My comment https://github.com/Sommerregen/grav-plugin-toc/issues/8#issuecomment-274003019 was already using the development branch.  So no, not working.

**Comment by Sommerregen** [comment] 2017-04-08 17:49
Ah, ok. Sorry, unfortunately then you have to be more patient. I'm entirely busy with other projects and my "real" work. Feel free to submit pull request. I will be happy to merge them 😃 .

**Comment by Sommerregen** [comment] 2017-06-12 17:46
@lid3rs I published a new release today, that fixes your error and includes the feature requested here in the issue.

**Closed as completed by Sommerregen** 2017-06-12 17:46 UTC
Labels: enhancement, fixed in repo

**Comment by rhukster** [comment] 2017-07-07 00:30
I'm not entirely sure this is working as expected.  I want to display the TOC in a sidebar, and strip it out of the content.  What is the best way to achieve that?

**Comment by Sommerregen** [comment] 2017-07-07 09:40
@rhukster Do it just in Twig with `{{ page.content|toc }}`. No need to include `[TOC]` in your md files. If you think that's an unexpected behaviour, please let me know, what you expect and I will change it (better open a new issue for that).

**Comment by rhukster** [comment] 2017-07-07 21:52
When I call `{{ page.content|toc }}` it simply outputs the full content. I did quickly look over your code and it seems that you have a regex check to ensure the existence of `[TOC]`  or `[MINITOC]` else it returns the page contents (not the TOC):

https://github.com/Sommerregen/grav-plugin-toc/blob/develop/classes/Toc.php#L217-L223

**Comment by Sommerregen** [comment] 2017-07-09 18:07
@rhukster Ah, right. I totally forgot about that. Well, you can use the `{{ page.content|tocify }}` filter instead. It gives you a list, but it is actually not the thing you want.

**Comment by rhukster** [comment] 2017-07-09 18:17
Does `|tocify` provide information to use for indent levels?  I would need to rebuild the unordered list like you do with `|toc`, don't have it in front of me right now, but i seem to remember it didn't.

**Comment by Sommerregen** [comment] 2017-07-10 19:19
@rhukster See my comment https://github.com/Sommerregen/grav-plugin-toc/issues/8#issuecomment-155168799 ☝️ . You get

```php
['tag' => ..., 'level' => ..., 'indent' => ..., 'text' => ..., 'id' => ...]
```

However, you cant jump to the content from a custom generated TOC as the markup for the headings in the page content has not been injected yet. 

I'm busy in the next days and will be on holidays for a while. Feel free to provide a PR if you like.
